CREATE TABLE BOARD1(
	IDX			INT			AUTO_INCREMENT		PRIMARY KEY,
	PW				VARCHAR(50),
	NAME			VARCHAR(50),
	EMAIL			VARCHAR(100),
	HOMEPAGE		VARCHAR(255),
	SUBJECT		VARCHAR(255),
	MEMO			TEXT,
	FILE1			VARCHAR(255),
	FILE2			VARCHAR(255),
	REG_DAY		DATE
);

DESC BOARD1;

SELECT * FROM BOARD1;

DELETE FROM BOARD1;

DROP TABLE BOARD1;